# Generated by Django 4.2.29 on 2026-03-24 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='capacidad_total',
        ),
        migrations.RemoveField(
            model_name='tipoticket',
            name='evento',
        ),
        migrations.AddField(
            model_name='evento',
            name='capacidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evento',
            name='organizador',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.CreateModel(
            name='EventoTipoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
                ('tipo_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.tipoticket')),
            ],
            options={
                'unique_together': {('evento', 'tipo_ticket')},
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='tipos_ticket',
            field=models.ManyToManyField(related_name='eventos', through='eventos.EventoTipoTicket', to='eventos.tipoticket'),
        ),
    ]
