# Generated by Django 4.2.29 on 2026-03-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_remove_evento_capacidad_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='latitud',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lugar',
            name='longitud',
            field=models.FloatField(default=0.0),
        ),
    ]
